[package]
name = "wordle-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wordle-engine = { path = "../wordle-engine" }
rayon = "1.5.1"
itertools = "0.10.3"

[profile.release]
lto = true
